#Modify lines indicated with MODIFY
__default__:
  queue: 'windfall' #MODIFY
  group: '' #MODIFY
  M: '' #MODIFY
  walltime: 'walltime=04:00:00'
  select: 'select=1:ncpus=12:mem=100gb'
  m: 'bea'
  o: 'out/{rule}.{wildcards}.out'
  e: 'err/{rule}.{wildcards}.err'

#rename:
#  walltime: '01:00:00'
#  mem: '1000mb'




