configfile: "config/config.yml"

rule all:
    input:
        expand("input/{sample}_host_removed_R1_val_1.fq", sample=config["samples"]),
        expand("results/metaphlan/{sample}_profiles.txt", sample=config["samples"]),        
        expand("results/kraken2/{sample}_profiles.txt", sample=config["samples"]),

##### workflow starts here

rule trimGalore:
    input:
        f1="input/{base}_R1.fastq.gz",
        f2="input/{base}_R2.fastq.gz",
    params:
        qvalue=20,
        length=20,
        bowtiename="{base}_host_removed_R%.fastq.gz",
        sampleName="input/{base}",
        hdb="databases/GRCh38_noalt_as/GRCh38_noalt_as",
    output:
        o1="input/{base}_host_removed_R1_val_1.fq", 
    shell:
        """
        set +eu
        source ~/.bashrc
        conda activate metaphlan3 


        #bowtie2 -p 8 -x {params.hdb} -1 {input.f1} -2 {input.f2} --un-conc-gz input/{params.bowtiename}  
       
        trim_galore --paired --dont_gzip -o input --fastqc {params.sampleName}_host_removed_R1.fastq.gz {params.sampleName}_host_removed_R2.fastq.gz
        """

rule metaphlan:
    input:
        f1="input/{base}_host_removed_R1_val_1.fq",
    output:
        "results/metaphlan/{base}_profiles.txt",
    shell:
        """
        set +eu
        source ~/.bashrc
        conda activate metaphlan3

        metaphlan {input.f1} --input_type fastq > {output}
        """

rule kraken2:
    input:
        f1="input/{base}_host_removed_R1_val_1.fq",
    params:
        f2="input/{base}_host_removed_R2_val_2.fq",
        db="databases/k2_pluspf_20210127"
    output:
        "results/kraken2/{base}_profiles.txt",
    shell:
        """
        set +eu
        source ~/.bashrc
        conda activate metaphlan3

        kraken2 --paired --db {params.db} --report {output} {input.f1} {params.f2}
        """



